version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/src/frontend/Census.WebApp/ClientApp"
    schedule:
      interval: weekly
