<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Neo4jClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Census.Shared\Census.Shared.csproj" />
    <ProjectReference Include="..\Census.FamilyTree.Application\Census.FamilyTree.Application.csproj" />
    <ProjectReference Include="..\Census.FamilyTree.Domain\Census.FamilyTree.Domain.csproj" />
  </ItemGroup>

</Project>
